### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by JakeDluhy** [JakeDluhy/redux-dialog#2]
There are a couple things that I think should be added to start making this a better open source project.

- [x] CHANGELOG.md (will point to tags)
- [x] CONTRIBUTING.md
- [x] LICENSE.md
- [x] CODE_OF_CONDUCT.md
- [ ] Linting
- [ ] Tests
- [ ] Switch from webpack to rollup

I'm also going to start tagging within Github, and am going to be more active in reviewing feature requests.

Feel free to make any additional suggestions. I'm pretty new at this =)
Tagging people who were interested in additional features for `redux-dialog` @negomi @cpBurn @nhagan @pawelniewie @romseguy @alexicum @pavveu

**Comment by pawelniewie** [comment]
What's rollup and why would you want to switch from a well known webpack? Just curious first time I hear about it.

**Comment by JakeDluhy** [comment]
It's another module builder. I really don't know a whole lot about it, but the refrain that I've heard is that "Webpack is for apps, Rollup is for libraries". It's supposed to be better because it pulls everything into a single bundle that gets evaluated at once, instead of multiple functions like webpack. (You lose things like HMR and code splitting, which aren't necessary for libraries). https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

I'm curious though, since webpack 3 introduces scope hoisting if that will be the same or better as implementing rollup! https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b
